In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [2]:
A = np.array([[1,2],
             [3,4]])

B = np.array([
    
             [[1,2],
             [3,4]],
    
            [[1,1],
             [1,1]]
        
             ])

print("A@B",A@B)
print("B@A",B@A)
print("A@A",A@A)
print("B@B",B@B)


A@B [[[ 7 10]
  [15 22]]

 [[ 3  3]
  [ 7  7]]]
B@A [[[ 7 10]
  [15 22]]

 [[ 4  6]
  [ 4  6]]]
A@A [[ 7 10]
 [15 22]]
B@B [[[ 7 10]
  [15 22]]

 [[ 2  2]
  [ 2  2]]]


<font color="red"> A@B works even when one array is 3D (i.e. a stack of matrices) -- > Gives the stack of results of each matrix multiplication</font>

In [1]:
C = np.arange(1,12+1).reshape(6,2)
C

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [3]:
C.ravel(order='F').reshape(1,2,-1)

array([[[ 1,  3,  5,  7,  9, 11],
        [ 2,  4,  6,  8, 10, 12]]])