# Keras with TensorFlow Course - Python Deep Learning and Neural Networks for Beginners Tutorial
https://www.youtube.com/watch?v=qFJeN9V1ZsI

### Things I learn (I will put a small note or a topic here)
1. sk learn shuffle function
2. sk learn pre processing MinMaxScaler
3. in Transformations : fit, transform and fit_transform
4. Sequential model\
batch_size = how many examples when stochastic GD\
epochs = how many round should go through entire dataset\
validation_split=0.1

In [1]:
#sk learn shuffle thing :: shuffling two lists
import numpy as np
from sklearn.utils import shuffle
nums = []
numSquareds = []
for i in range(10):
    nums.append(i)
    numSquareds.append(i**2)
    
nums,numSquareds = shuffle(nums,numSquareds)

print(nums,numSquareds)

[4, 9, 2, 6, 0, 3, 7, 1, 5, 8] [16, 81, 4, 36, 0, 9, 49, 1, 25, 64]


## Keras Sequential model

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

In [3]:
physical_devices = tf.config.experimental.list_physical_devices('GPU')
print("Number of GPUs found", len(physical_devices))

Number of GPUs found 0


Go see how to configure the GPUs to tensorflow here:\
https://www.youtube.com/watch?v=hHWkvEcDBO0\
Has to download 2.5GB!

In [4]:
model = Sequential([
    Dense(units=16, input_shape=(1,),activation='relu'),
    Dense(units=32,activation='relu'),
    Dense(units=2,activation='softmax')
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.compile(optimizer=Adam(learning_rate=1e-4),loss='categorical_crossentropy',metrics=['accuracy'])

In [6]:
#generate some data
x = 2*np.random.rand(1000)-1
y = np.logical_and(x>-0.5,x<0.5).astype(np.int16).reshape(-1,1)


y = np.concatenate((y,y==0),axis=1)
x=x.reshape(-1,1)
print(x.shape)

(1000, 1)


In [7]:
#pre-processing :: bcz original x in [-1,1]
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x = scaler.fit_transform(x.reshape(-1,1))

#training the network
model.fit(x=x,y=y.reshape(-1,2),batch_size=10,epochs=30,verbose=2,shuffle=1,validation_split=0.1) #shuffle =1 is default

Epoch 1/30
90/90 - 1s - loss: 0.6956 - accuracy: 0.4700 - val_loss: 0.6962 - val_accuracy: 0.4400 - 720ms/epoch - 8ms/step
Epoch 2/30
90/90 - 0s - loss: 0.6936 - accuracy: 0.3656 - val_loss: 0.6939 - val_accuracy: 0.3700 - 140ms/epoch - 2ms/step
Epoch 3/30
90/90 - 0s - loss: 0.6918 - accuracy: 0.2967 - val_loss: 0.6924 - val_accuracy: 0.2900 - 120ms/epoch - 1ms/step
Epoch 4/30
90/90 - 0s - loss: 0.6901 - accuracy: 0.2911 - val_loss: 0.6906 - val_accuracy: 0.3900 - 110ms/epoch - 1ms/step
Epoch 5/30
90/90 - 0s - loss: 0.6882 - accuracy: 0.5556 - val_loss: 0.6883 - val_accuracy: 0.5800 - 110ms/epoch - 1ms/step
Epoch 6/30
90/90 - 0s - loss: 0.6860 - accuracy: 0.6822 - val_loss: 0.6860 - val_accuracy: 0.6800 - 110ms/epoch - 1ms/step
Epoch 7/30
90/90 - 0s - loss: 0.6837 - accuracy: 0.7556 - val_loss: 0.6836 - val_accuracy: 0.7300 - 150ms/epoch - 2ms/step
Epoch 8/30
90/90 - 0s - loss: 0.6815 - accuracy: 0.7522 - val_loss: 0.6816 - val_accuracy: 0.7500 - 130ms/epoch - 1ms/step
Epoch 9/30
90/90

In [8]:
model.get_weights()

[array([[ 0.35931495,  0.12848742,  0.7207956 , -0.20558265, -0.4552104 ,
         -0.26271373,  0.14366134, -0.02570808,  0.05883958, -0.39028662,
          0.618193  , -0.47208375,  0.7070187 , -0.40285647,  0.19298603,
         -0.5796441 ]], dtype=float32),
 array([-0.07501116, -0.06256168, -0.06683046,  0.        ,  0.        ,
         0.        , -0.06992622,  0.14485767,  0.04823666,  0.        ,
        -0.04939071,  0.        , -0.05865476,  0.        , -0.09205218,
         0.        ], dtype=float32),
 array([[ 0.27693406, -0.46226984, -0.29156289,  0.21667692,  0.2956624 ,
          0.15341337, -0.27280793, -0.23762143, -0.0234685 , -0.01319262,
          0.23911853,  0.005463  ,  0.39770186, -0.15649302, -0.07098107,
          0.04247295,  0.26780215,  0.1790256 ,  0.13877298, -0.15123531,
         -0.25245515,  0.1817055 ,  0.19681732,  0.38815767,  0.05304768,
          0.13328318,  0.29823276,  0.34159508,  0.15031905,  0.10931849,
         -0.09190903, -0.35275388],
 

### [SELF] Try and encoder decoder neural network to practice

In [22]:
endec_model = Sequential([
    Dense(units=20,input_shape=(10,),activation='relu'),
    
    Dense(units=5,activation='relu'),
    
    Dense(units=10,activation='relu')
]);
   



endec_model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 20)                220       
                                                                 
 dense_19 (Dense)            (None, 5)                 105       
                                                                 
 dense_20 (Dense)            (None, 10)                60        
                                                                 
Total params: 385
Trainable params: 385
Non-trainable params: 0
_________________________________________________________________


In [23]:
endec_model.compile(optimizer=Adam(learning_rate=1e-3),metrics=["accuracy"],loss='mean_squared_error')

#generate some data
m=1000_00
x1 = np.random.rand(m)
x2 = np.random.rand(m)
x3 = np.random.rand(m)
x4 = np.random.rand(m)
x5 = np.random.rand(m)

x6 = x1 + x2 + x3
x7 = x1 - x2 + x4 -x5
x8 = x7 - x6 + x3
x9 = x7 -x3
x10 = x5 + x2

x_train = np.array([x1,x2,x3,x4,x5,x6,x7,x8,x9,x10]).T


#train
endec_model.fit(x=x_train,y=x_train,epochs=100,verbose=2)


Epoch 1/100
3125/3125 - 2s - loss: 0.2837 - accuracy: 0.9228 - 2s/epoch - 789us/step
Epoch 2/100
3125/3125 - 2s - loss: 0.2579 - accuracy: 0.9751 - 2s/epoch - 704us/step
Epoch 3/100
3125/3125 - 2s - loss: 0.2578 - accuracy: 0.9747 - 2s/epoch - 694us/step
Epoch 4/100
3125/3125 - 2s - loss: 0.2578 - accuracy: 0.9744 - 2s/epoch - 685us/step
Epoch 5/100
3125/3125 - 2s - loss: 0.2578 - accuracy: 0.9736 - 2s/epoch - 707us/step
Epoch 6/100
3125/3125 - 2s - loss: 0.2578 - accuracy: 0.9736 - 2s/epoch - 714us/step
Epoch 7/100
3125/3125 - 2s - loss: 0.2578 - accuracy: 0.9731 - 2s/epoch - 697us/step
Epoch 8/100
3125/3125 - 2s - loss: 0.2578 - accuracy: 0.9730 - 2s/epoch - 685us/step
Epoch 9/100
3125/3125 - 2s - loss: 0.2578 - accuracy: 0.9732 - 2s/epoch - 723us/step
Epoch 10/100
3125/3125 - 2s - loss: 0.2578 - accuracy: 0.9728 - 2s/epoch - 720us/step
Epoch 11/100
3125/3125 - 2s - loss: 0.2578 - accuracy: 0.9727 - 2s/epoch - 726us/step
Epoch 12/100
3125/3125 - 3s - loss: 0.2578 - accuracy: 0.9726 -

Epoch 97/100
3125/3125 - 2s - loss: 0.2571 - accuracy: 0.9806 - 2s/epoch - 714us/step
Epoch 98/100
3125/3125 - 2s - loss: 0.2571 - accuracy: 0.9805 - 2s/epoch - 723us/step
Epoch 99/100
3125/3125 - 2s - loss: 0.2571 - accuracy: 0.9807 - 2s/epoch - 717us/step
Epoch 100/100
3125/3125 - 2s - loss: 0.2571 - accuracy: 0.9806 - 2s/epoch - 714us/step


In [24]:
x_test = np.random.rand(10).reshape(-1,10)
endec_model.predict(x=x_test)

1/1 [==============================] - 0s 47ms/step


array([[0.3606714 , 0.16260089, 0.32237023, 0.8030821 , 0.31838685,
        0.8554546 , 0.        , 0.        , 0.        , 0.5066706 ]],
      dtype=float32)

In [25]:
x_test

array([[0.41039904, 0.07762857, 0.33721956, 0.75953753, 0.34372247,
        0.93648009, 0.92994584, 0.54463242, 0.85516277, 0.40502504]])